[GITHUB]
# Your GitHub username
USERNAME = ""
# Your GitHub personal access token, needed permissions:
#   - repo (Full control of private repositories)
PAT = ""

[GITEA]
# Your Gitea username
USERNAME = ""
# Your Gitea hostname, starts with "http://" or "https://"
HOST = "https://"
# Your Gitea personal access token, needed permissions:
#   - repository: Read and Write
#   - organization: Read and Write
PAT = ""
