name: Docker Build and Push

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          DATE_TAG=$(TZ=Asia/Singapore date +'%Y.%m.%d')
          docker build -t --no-cache ${{ secrets.DOCKER_USERNAME }}/github-mirror-gitea:$DATE_TAG -t ${{ secrets.DOCKER_USERNAME }}/github-mirror-gitea:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/github-mirror-gitea:$DATE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/github-mirror-gitea:latest